nelmio_api_doc:
    documentation:
        servers:
          - url: http://localhost:8000/api/login_check
            description:
        info:
            title: Challenge AIVO
            description: ~
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)
        host_patterns:
            - ^api\.